<div class="group flex max-md:flex-col justify-center gap-2">
    <article class="group/article relative w-full rounded-xl overflow-hidden md:group-hover:not-[&:hover]:w-[20%] md:group-focus-within:not-[&:focus-within:not(&:hover)]:w-[20%] transition-all duration-300 ease-[cubic-bezier(.5,.85,.25,1.15)] before:absolute before:inset-x-0 before:bottom-0 before:h-1/3 before:bg-linear-to-t before:from-black/50 before:transition-opacity md:before:opacity-0 md:hover:before:opacity-100 focus-within:before:opacity-100 after:opacity-0 md:group-hover:not-[&:hover]:after:opacity-100 md:group-focus-within:not-[&:focus-within:not(&:hover)]:after:opacity-100 after:absolute after:inset-0 after:bg-white/30 after:backdrop-blur after:transition-all focus-within:ring focus-within:ring-indigo-300">
        <a class="absolute inset-0 text-white z-10" href="#0">
            <span class="absolute inset-x-0 bottom-0 text-lg font-medium p-6 md:px-12 md:py-8 md:whitespace-nowrap md:truncate md:opacity-0 group-hover/article:opacity-100 group-focus-within/article:opacity-100 md:translate-y-2 group-hover/article:translate-y-0 group-focus-within/article:translate-y-0 transition duration-200 ease-[cubic-bezier(.5,.85,.25,1.8)] group-hover/article:delay-300 group-focus-within/article:delay-300">"Pengimplementasian Sapta Pesona menuju pariwisata yang berkelanjutan"</span>
        </a>
        <img class="object-cover h-96 md:h-132 w-full md:group-hover:not-[&:hover]:scale-150 md:hover:scale-100 origin-center transition-transform duration-500 ease-[cubic-bezier(.5,.85,.25,1.15)]" src="images/pantai.jpg" width="960" height="480" alt="Image 01">
    </article>
    <article class="group/article relative w-full rounded-xl overflow-hidden md:group-hover:not-[&:hover]:w-[20%] md:group-focus-within:not-[&:focus-within:not(&:hover)]:w-[20%] transition-all duration-300 ease-[cubic-bezier(.5,.85,.25,1.15)] before:absolute before:inset-x-0 before:bottom-0 before:h-1/3 before:bg-linear-to-t before:from-black/50 before:transition-opacity md:before:opacity-0 md:hover:before:opacity-100 focus-within:before:opacity-100 after:opacity-0 md:group-hover:not-[&:hover]:after:opacity-100 md:group-focus-within:not-[&:focus-within:not(&:hover)]:after:opacity-100 after:absolute after:inset-0 after:bg-white/30 after:backdrop-blur after:transition-all focus-within:ring focus-within:ring-indigo-300">
        <a class="absolute inset-0 text-white z-10" href="#0">
            <span class="absolute inset-x-0 bottom-0 text-lg font-medium p-6 md:px-12 md:py-8 md:whitespace-nowrap md:truncate md:opacity-0 group-hover/article:opacity-100 group-focus-within/article:opacity-100 md:translate-y-2 group-hover/article:translate-y-0 group-focus-within/article:translate-y-0 transition duration-200 ease-[cubic-bezier(.5,.85,.25,1.8)] group-hover/article:delay-300 group-focus-within/article:delay-300">"Pelayanan yang ramah dengan harga yang terjangkau"</span>
        </a>
        <img class="object-cover h-96 md:h-132 w-full md:group-hover:not-[&:hover]:scale-150 md:hover:scale-100 origin-center transition-transform duration-500 ease-[cubic-bezier(.5,.85,.25,1.15)]" src="images/pura.jpg" width="960" height="480" alt="Image 02">
    </article>
    <article class="group/article relative w-full rounded-xl overflow-hidden md:group-hover:not-[&:hover]:w-[20%] md:group-focus-within:not-[&:focus-within:not(&:hover)]:w-[20%] transition-all duration-300 ease-[cubic-bezier(.5,.85,.25,1.15)] before:absolute before:inset-x-0 before:bottom-0 before:h-1/3 before:bg-linear-to-t before:from-black/50 before:transition-opacity md:before:opacity-0 md:hover:before:opacity-100 focus-within:before:opacity-100 after:opacity-0 md:group-hover:not-[&:hover]:after:opacity-100 md:group-focus-within:not-[&:focus-within:not(&:hover)]:after:opacity-100 after:absolute after:inset-0 after:bg-white/30 after:backdrop-blur after:transition-all focus-within:ring focus-within:ring-indigo-300">
        <a class="absolute inset-0 text-white z-10" href="#0">
            <span class="absolute inset-x-0 bottom-0 text-lg font-medium p-6 md:px-12 md:py-8 md:whitespace-nowrap md:truncate md:opacity-0 group-hover/article:opacity-100 group-focus-within/article:opacity-100 md:translate-y-2 group-hover/article:translate-y-0 group-focus-within/article:translate-y-0 transition duration-200 ease-[cubic-bezier(.5,.85,.25,1.8)] group-hover/article:delay-300 group-focus-within/article:delay-300">"Grooming yang profesional, agar first impression yang baik tercipta"</span>
        </a>
        <img class="object-cover h-96 md:h-132 w-full md:group-hover:not-[&:hover]:scale-150 md:hover:scale-100 origin-center transition-transform duration-500 ease-[cubic-bezier(.5,.85,.25,1.15)]" src="images/sawah.jpg" width="960" height="480" alt="Image 03">
    </article>                                
</div>